# display/analyze.py
display_analyze__display__div = 'display_analyze__display__div'
display_analyze__venn_display__div = 'display_analyze__venn_display__div'
display_analyze__clustergram_display__div = 'display_analyze__clustergram_display__div'
display_analyze__prerec_display__div = 'display_analyze__prerec_display__div'
display_analyze__summary_display__div = 'display_analyze__summary_display__div'
display_analyze__filename_summary_display__div = 'display_analyze__filename_summary_display__div'
display_analyze__metadata_summary_display__div = 'display_analyze__metadata_summary_display__div'
display_analyze__raw_summary_display__div = 'display_analyze__raw_summary_display__div'

# display/upload.py
display_upload__display__div = 'display_upload__display__div'
display_upload__compare_set_summary_card__div = 'display_upload__compare_set_summary_card__div'
display_upload__golden_set_summary_card__div = 'display_upload__golden_set_summary_card__div'
display_upload__metadata_summary_card__div = 'display_upload__metadata_summary_card__div'
display_upload__regions_summary_card__div = 'display_upload__regions_summary_card__div'

# display/welcome.py
display_welcome__display__div = 'display_welcome__display__div'

# navbar/analyze/analyze.py
navbar_analyze_analyze__analysis_type__radio_items = 'navbar_analyze_analyze__analysis_type__radio_items'
navbar_analyze_analyze__filter_pass__checklist = 'navbar_analyze_analyze__filter_pass__checklist'
navbar_analyze_analyze__genomic_regions__dropdown = 'navbar_analyze_analyze__genomic_regions__dropdown'
navbar_analyze_analyze__inside_outside_regions__radio_items = 'navbar_analyze_analyze__inside_outside_regions__radio_items'
navbar_analyze_analyze__on_chromosome__dropdown = 'navbar_analyze_analyze__on_chromosome__dropdown'
navbar_analyze_analyze__variant_type__dropdown = 'navbar_analyze_analyze__variant_type__dropdown'

# navbar/analyze/clustergram.py
navbar_analyze_clustergram__submit__button = 'navbar_analyze_clustergram__submit__button'
navbar_analyze_clustergram__options__div = 'navbar_analyze_clustergram__options__div'
navbar_analyze_clustergram__grouping_columns__dropdown = 'navbar_analyze_clustergram__grouping_columns__dropdown'
navbar_analyze_clustergram__grouping_method__dropdown = 'navbar_analyze_clustergram__grouping_method__dropdown'
navbar_analyze_clustergram__labeling_columns__dropdown = 'navbar_analyze_clustergram__labeling_columns__dropdown'
navbar_analyze_clustergram__labeling_method__checklist = 'navbar_analyze_clustergram__labeling_method__checklist'
navbar_analyze_clustergram__heatmap_colors__dropdown = 'navbar_analyze_clustergram__heatmap_colors__dropdown'
navbar_analyze_clustergram__font_size__input = 'navbar_analyze_clustergram__font_size__input'

# navbar/analyze/prerec.py
navbar_analyze_prerec__submit__button = 'navbar_analyze_prerec__submit__button'
navbar_analyze_prerec__options__div = 'navbar_analyze_prerec__options__div'
navbar_analyze_prerec__grouping_columns__dropdown = 'navbar_analyze_prerec__grouping_columns__dropdown'
navbar_analyze_prerec__grouping_method__dropdown = 'navbar_analyze_prerec__grouping_method__dropdown'
navbar_analyze_prerec__labeling_columns__dropdown = 'navbar_analyze_prerec__labeling_columns__dropdown'
navbar_analyze_prerec__coloring_columns__dropdown = 'navbar_analyze_prerec__coloring_columns__dropdown'
navbar_analyze_prerec__shaping_columns__dropdown = 'navbar_analyze_prerec__shaping_columns__dropdown'
navbar_analyze_prerec__font_size__input = 'navbar_analyze_prerec__font_size__input'

# navbar/analyze/summary.py
navbar_analyze_summary__options__div = 'navbar_analyze_summary__options__div'
navbar_analyze_summary__type__radio_items = 'navbar_analyze_summary__type__radio_items'

navbar_analyze_summary__filename_submit__button = 'navbar_analyze_summary__filename_submit__button'
navbar_analyze_summary__filename_options__div = 'navbar_analyze_summary__filename_options__div'
navbar_analyze_summary__filename_set__dropdown = 'navbar_analyze_summary__filename_set__dropdown'
navbar_analyze_summary__filename_visualization__div = 'navbar_analyze_summary__filename_visualization__div'
navbar_analyze_summary__font_size__div = 'navbar_analyze_summary__font_size__div'
navbar_analyze_summary__font_size__input = 'navbar_analyze_summary__font_size__input'
navbar_analyze_summary__filename_download__button = 'navbar_analyze_summary__filename_download__button'
navbar_analyze_summary__filename_download__download = 'navbar_analyze_summary__filename_download__download'

navbar_analyze_summary__metadata_submit__button = 'navbar_analyze_summary__metadata_submit__button'
navbar_analyze_summary__metadata_options__div = 'navbar_analyze_summary__metadata_options__div'
navbar_analyze_summary__metadata_grouping_columns__dropdown = 'navbar_analyze_summary__metadata_grouping_columns__dropdown'
navbar_analyze_summary__metadata_grouping_method__dropdown = 'navbar_analyze_summary__metadata_grouping_method__dropdown'
navbar_analyze_summary__metadata_all__checklist = 'navbar_analyze_summary__metadata_all__checklist'
navbar_analyze_summary__metadata_pivoting_columns__dropdown = 'navbar_analyze_summary__metadata_pivoting_columns__dropdown'
navbar_analyze_summary__metadata_download__button = 'navbar_analyze_summary__metadata_download__button'
navbar_analyze_summary__metadata_download__download = 'navbar_analyze_summary__metadata_download__download'

navbar_analyze_summary__raw_submit__button = 'navbar_analyze_summary__raw_submit__button'
navbar_analyze_summary__raw_options__div = 'navbar_analyze_summary__raw_options__div'
navbar_analyze_summary__raw_type__dropdown = 'navbar_analyze_summary__raw_type__dropdown'
navbar_analyze_summary__raw_download__button = 'navbar_analyze_summary__raw_download__button'
navbar_analyze_summary__raw_download__download = 'navbar_analyze_summary__raw_download__download'

# navbar/analyze/venn.py
navbar_analyze_venn__submit__button = 'navbar_analyze_venn__submit__button'
navbar_analyze_venn__options__div = 'navbar_analyze_venn__options__div'
navbar_analyze_venn__grouping_columns__dropdown = 'navbar_analyze_venn__grouping_columns__dropdown'
navbar_analyze_venn__grouping_method__dropdown = 'navbar_analyze_venn__grouping_method__dropdown'
navbar_analyze_venn__prefer_pseudovenn__checklist = 'navbar_analyze_venn__prefer_pseudovenn__checklist'
navbar_analyze_venn__font_size__input = 'navbar_analyze_venn__font_size__input'
navbar_analyze_venn__figure_download__button = 'navbar_analyze_venn__figure_download__button'
navbar_analyze_venn__figure_download__download = 'navbar_analyze_venn__figure_download__download'
navbar_analyze_venn__sites_download__button = 'navbar_analyze_venn__sites_download__button'
navbar_analyze_venn__sites_download__download = 'navbar_analyze_venn__sites_download__download'

# navbar/navbar.py
navbar_navbar__tabs__tabs = 'navbar_navbar__tabs__tabs'
navbar_navbar__first_visit_for_tabs__store = 'navbar_navbar__first_visit_for_tabs__store'
navbar_navbar__first_visit_for_buttons__store = 'navbar_navbar__first_visit_for_buttons__store'
navbar_navbar__session_id__store = 'navbar_navbar__session_id__store'

# navbar/upload.py
navbar_upload__compare_set__upload = 'navbar_upload__compare_set__upload'
navbar_upload__compare_set_upload_result__div = 'navbar_upload__compare_set_upload_result__div'
navbar_upload__golden_set__upload = 'navbar_upload__golden_set__upload'
navbar_upload__golden_set_upload_result__div = 'navbar_upload__golden_set_upload_result__div'
navbar_upload__metadata__upload = 'navbar_upload__metadata__upload'
navbar_upload__metadata_upload_result__div = 'navbar_upload__metadata_upload_result__div'
navbar_upload__regions__upload = 'navbar_upload__regions__upload'
navbar_upload__regions_upload_result__div = 'navbar_upload__regions_upload_result__div'
navbar_upload__go_to_analyze__button = 'navbar_upload__go_to_analyze__button'
navbar_upload__compare_set_valid__store = 'navbar_upload__compare_set_valid__store'
navbar_upload__golden_set_valid__store = 'navbar_upload__golden_set_valid__store'
navbar_upload__metadata_valid__store = 'navbar_upload__metadata_valid__store'
navbar_upload__regions_valid__store = 'navbar_upload__regions_valid__store'

# navbar/welcome.py
navbar_upload__go_to_upload__button = 'navbar_upload__go_to_upload__button'
